version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    user: jenkins
    env_file:
      - .env
    ports:
      - 0.0.0.0:8000:8080
    volumes:
      - ./jcasc:/var/jenkins_config/casc_configs:Z
      - ./data:/var/jenkins_home:Z
    networks:
      - jenkins
    restart: on-failure

networks:
  jenkins:
    name: jenkins
    driver: bridge
