version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    user: jenkins
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./jcasc:/var/jenkins_config/casc_configs
      - ./data:/var/jenkins_home
    networks:
      - jenkins
    restart: on-failure

networks:
  jenkins:
    name: jenkins
    driver: bridge
