---
  # Установка необходимых пакетов для успешной работы Jenkins Agent:
  - name: Installing required packages on OpenSUSE
    zypper: 
      name: "{{ opensuse_agent_packages_list }}"
      state: present
      update_cache: yes

  # Создание группы пользователя в системе для успешной работы Jenkins Agent:
  - name: Creating a specific group on OpenSUSE
    group:
      name: "{{ jenkins_agent_group }}"
      state: present

  # Создание пользователя в системе для выполнения последующих задач в роли Jenkins Agent:
  - name: Creating user for future actions on OpenSUSE
    user:
      name: "{{ jenkins_agent_user }}"
      shell: "/bin/bash"
      state: present
      home: "{{ item.main }}"
      group: "{{ jenkins_agent_group }}"
    with_items: 
      - "{{ jenkins_agent_directory }}"

  # Создание необходимых директорий для хранения данных и конфигурации Jenkins Agent:
  - name: Creating directories on OpenSUSE
    file:
      state: directory
      path: "{{ item.path }}"
      mode: "{{ jenkins_agent_directory_mode }}"
      owner: "{{ jenkins_agent_user }}"
      group: "{{ jenkins_agent_group }}"
    with_items:
      - { path: "{{ jenkins_agent_directory }}" }

  # Добавление публичного SSH-ключа для работы с Jenkins Agent:
  - name: Add SSH public key for specific user on OpenSUSE
    authorized_key:
      user: "{{ jenkins_agent_user }}"
      state: present
      key: "{{ jenkins_agent_public_key }}"
      validate_certs: false

  # Предоставление прав sudo для созданного ранее пользователя, для работы Jenkins Agent:
  - name: Setting sudo permissions for the created user on OpenSUSE
    template:
      src: "templates/jenkins-agent"
      dest: "/etc/sudoers.d/{{ jenkins_agent_user }}"
