---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  tasks:
    # Данный шаг вызывает роль manual-jenkins-agent для прогона тестов с помощью Molecule:
    - name: "Include manual-jenkins-agent role for testing"
      include_role:
        name: "manual-jenkins-agent"
