---
dependency:
  name: galaxy

driver:
  name: ec2

platforms:
  - name: "ubuntu20.04"
    aws_profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20240918" # Ubuntu 20.04
    image_owner: "099720109477"
    instance_type: "{{ aws_instance_type }}"
    vpc_id: "{{ aws_vpc_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    volumes: []
    security_groups: []
    key_inject_method: "{{ aws_key_method }}"
    ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
    ssh_port: 22
    assign_public_ip: true
    boot_wait_seconds: 120
    key_name: "{{ aws_custom_key_name }}"
    private_key_path: "{{ aws_local_private_key }}"
    public_key_path: "{{ aws_local_public_key }}"
    security_group_name: "{{ aws_secruity_group_name }}"

  - name: "ubuntu22.04"
    aws_profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240925" # Ubuntu 22.04
    image_owner: "099720109477"
    instance_type: "{{ aws_instance_type }}"
    vpc_id: "{{ aws_vpc_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    volumes: []
    security_groups: []
    key_inject_method: "{{ aws_key_method }}"
    ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
    ssh_port: 22
    assign_public_ip: true
    boot_wait_seconds: 120
    key_name: "{{ aws_custom_key_name }}"
    private_key_path: "{{ aws_local_private_key }}"
    public_key_path: "{{ aws_local_public_key }}"
    security_group_name: "{{ aws_secruity_group_name }}"

  - name: "ubuntu24.04"
    aws_profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_name: "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240906" # Ubuntu 24.04
    image_owner: "099720109477"
    instance_type: "{{ aws_instance_type }}"
    vpc_id: "{{ aws_vpc_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    volumes: []
    security_groups: []
    key_inject_method: "{{ aws_key_method }}"
    ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
    ssh_port: 22
    assign_public_ip: true
    boot_wait_seconds: 120
    key_name: "{{ aws_custom_key_name }}"
    private_key_path: "{{ aws_local_private_key }}"
    public_key_path: "{{ aws_local_public_key }}"
    security_group_name: "{{ aws_secruity_group_name }}"

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    links:
      group_vars: ../../../../group_vars/

verifier:
  name: ansible
