---
# Установка пакета Certbot со всеми зависимостями на DEB дистрибутивах:
- name: Installing required packages on DEB family distro
  package:
    name: "{{ certbot_packages_list }}"
    state: present
    update_cache: true

# Установка PIP-пакета, который необходим для корректной работы Certbot (только Ubuntu 20.04):
- name: Installing required packages for pip on DEB family distro
  pip:
    name: "{{ ubuntu_pip_packages_list}}"
    state: present
    executable: pip3
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

# Проверка того, был ли создан SSL-сертификат для запрашиваемого домена:
- name: Check if certificate already exists on DEB family distro
  stat:
    path: /etc/letsencrypt/live/{{ jenkins_nginx_domain | first }}/cert.pem
  register: letsencrypt_cert

# Создание сертификата для указанного домена, если таковой не был обнаружен:
- name: Generate new certificate if one doesn't exist on DEB family distro
  command: "{{ certificates_certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists
  changed_when: false

# Запуск сервиса Certbot, для отслеживания состояния сертификата:
- name: Starting Certbot.timer on DEB family distro
  systemd:
    name: certbot.timer
    state: started
    enabled: true
