---
# Вызов yaml файла для установки SSL-сертификатов на дистрибутивах семейства SUSE/RedHat:
- name: Invocation of the rpm.yaml task
  include_tasks: rpm.yaml
  when: (ansible_os_family == 'Suse') or (ansible_os_family == 'RedHat')

# Вызов yaml файла для установки SSL-сертификатов на дистрибутиве семейства Debian:
- name: Invocation of the deb.yaml task
  include_tasks: deb.yaml
  when: ansible_os_family == 'Debian'
