---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  tasks:
    # Данный шаг вызывает роль docker-jenkins-agent для прогона тестов:
    - name: "Include docker-jenkins-agent role for testing"
      include_role:
        name: "docker-jenkins-agent"
