---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian10
    image: mdd13/ansible-docker-debian:debian10
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    tmpfs:
      - /run
      - /tmp

  - name: debian11
    image: mdd13/ansible-docker-debian:debian11
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false

  - name: debian12
    image: mdd13/ansible-docker-debian:debian12
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false

  - name: ubuntu20.04
    image: mdd13/ansible-docker-ubuntu:ubuntu20.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu22.04
    image: mdd13/ansible-docker-ubuntu:ubuntu22.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu24.04
    image: mdd13/ansible-docker-ubuntu:ubuntu24.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    group_vars:
      all:
        docker_jenkins_agent_name: "docker-jenkins-agent"
        docker_jenkins_agent_image: "jenkins/ssh-agent:alpine"
        docker_jenkins_agent_ssh_port: "2222"
        docker_jenkins_agent_public_key: "ssh-rsa testpublickey"

verifier:
  name: ansible

lint: |
  yamllint -c ../../../.yamllint .
  ansible-lint .
