---
# Данный файл знаменует успешное завершение запускаемых ранее тестов:
- name: Verify
  hosts: all
  tasks:
    # Проверка доступности Jenkins после установки:
    - name: Checking Jenkins for availability
      uri:
        url: "http://127.1:8080"
        return_content: true
        status_code: 200
      register: output

    # Результат выполненной ранее проверки:
    - name: Output the result of a registered variable
      debug:
        msg: "{{ output.content }}"
