---
# Вызов предварительной роли system-prepare для полноценного запуска текущей:
- name: Import system-prepare role for running main role on RedHat family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Вызов предварительной роли system-docker для полноценного запуска текущей:
- name: Import system-docker role for running main role on RedHat family distro
  import_role:
    name: system-docker
    tasks_from: main

# Создание различных директорий для взаимодействия с Jenkins:
- name: Create Jenkins directories on Centos on RedHat family distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ jenkins_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
    recurse: true
  with_items:
    - {path: "{{ jenkins_data_dir }}"}
    - {path: "{{ jenkins_config_dir }}"}
    - {path: "{{ jenkins_docker_dir }}"}
  changed_when: false

# Копирование файлов из директории files и их последующая передача в директорию jenkins_config:
- name: Copy Docker files in directory jenkins_config on RedHat family distro
  copy:
    src: files/
    dest: "{{ jenkins_docker_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
  changed_when: false

# Копирование файлов из директории templates и их последующая передача в директорию jenkins_config:
- name: Copy CasC templates configs in directory jenkins_config on RedHat family distro
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_config_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
  with_fileglob:
    - ../templates/*.j2
  changed_when: false

# Запуск Jenkins с помощью docker-compose на удаленном узле:
- name: Run Jenkins via docker-compose on RedHat family distro
  command: docker-compose -f {{ jenkins_docker_dir }}/{{ jenkins_file_compose }} up -d --build --force-recreate
  register: docker_compose_output
  changed_when: false

# Результат вывода переменной на экран:
- name: The output result of our variable on RedHat family distro
  debug:
    var: docker_compose_output
