# Это альтернативный вариант запуска тех же тестов с помощью Molecule, только всё представлено в виде одной Job:

# on:
#   push:
#     branches:
#     - main

# jobs:
#   molecule-tests:
#     runs-on: ubuntu-latest
#     env:
#       PY_COLORS: 1
#       ANSIBLE_FORCE_COLOR: 1

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - uses: hadolint/hadolint-action@v3.1.0
#         with:
#           recursive: true
#           dockerfile: Dockerfile
#           ignore: "DL3008,SC3009"

#       - name: Set up Python 3.11
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11

#       - name: Install dependencies
#         run: |
#           python -m pip install --no-cache-dir --upgrade pip
#           pip install -r requirements.txt

#       - name: Define modified files for roles in ansible directory
#         uses: dorny/paths-filter@v2
#         id: changes
#         with:
#           filters: |
#             docker-jenkins:
#               - 'ansible/roles/docker-jenkins/**'
#             docker-jenkins-agent:
#               - 'ansible/roles/docker-jenkins-agent/**'
#             manual-jenkins:
#               - 'ansible/roles/manual-jenkins/**'
#             manual-jenkins-agent:
#               - 'ansible/roles/manual-jenkins-agent/**'
#             system-docker:
#               - 'ansible/roles/system-docker/**'
#             system-nginx:
#               - 'ansible/roles/system-nginx/**'
#             system-prepare:
#               - 'ansible/roles/system-prepare/**'

#       - name: Run molecule tests when content changes in docker-jenkins role
#         if: steps.changes.outputs.docker-jenkins == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/docker-jenkins

#       - name: Run molecule tests when content changes in docker-jenkins-agent role
#         if: steps.changes.outputs.docker-jenkins-agent == 'true'
#         run: |
#             molecule --version
#             molecule converge
#         working-directory: ansible/roles/docker-jenkins-agent

#       - name: Run molecule tests when content changes in manual-jenkins role
#         if: steps.changes.outputs.manual-jenkins == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/manual-jenkins

#       - name: Run molecule tests when content changes in manual-jenkins-agent role
#         if: steps.changes.outputs.manual-jenkins-agent == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/manual-jenkins-agent

#       - name: Run molecule tests when content changes in system-docker role
#         if: steps.changes.outputs.system-docker == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/system-docker

#       - name: Run molecule tests when content changes in system-nginx role
#         if: steps.changes.outputs.system-nginx == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/system-nginx

#       - name: Run molecule tests when content changes in system-prepare role
#         if: steps.changes.outputs.system-prepare == 'true'
#         run: |
#             molecule --version
#             molecule test
#         working-directory: ansible/roles/system-prepare
