---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: opensuse15.5
    image: mdd13/ansible-docker-suse:opensuse15.5
    pre_build_image: true
    privileged: true
    override_command: false
    cgroup_parent: docker.slice
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined

  - name: opensuse15.6
    image: mdd13/ansible-docker-suse:opensuse15.6
    pre_build_image: true
    privileged: true
    override_command: false
    cgroup_parent: docker.slice
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    group_vars:
      all:
        docker_jenkins_agent_name: "docker-jenkins-agent"
        docker_jenkins_agent_image: "jenkins/ssh-agent:alpine"
        docker_jenkins_agent_ssh_port: "2222"
        docker_jenkins_agent_public_key: "ssh-rsa testpublickey"

verifier:
  name: ansible
