---
# # Активация маршрутизации в системе, для будущей сборки образа Docker через Ansible:
- name: Active routing for build docker image on RedHat family distro
  command: echo net.ipv4.ip_forward=1 > /etc/sysctl.conf
  changed_when: false

# Создание группы с именем docker для последующего использования в системе:
- name: Ensure that docker group exists on RedHat family distro
  group:
    name: docker
    state: present

# Добавление репозитория для последующей установки Docker в системе:
- name: Add package repository address on RedHat family distro
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true

# Загрузка дополнительного RPM-пакета из Интернета, для установки Docker в системе (актуально для Centos 9):
- name: Install a libcgroup package on RedHat family distro
  yum:
    name: "{{ redhat_docker_libcgroup }}"
    disable_gpg_check: true
    state: present
  when: 
    - ansible_distribution in ['CentOS', 'RedHat', 'Red Hat Enterprise Linux']
    - ansible_distribution_version is version('9', '>=')

# Установка Docker с помощью пакетного менеджера:
- name: Install Docker on RedHat family distro
  yum:
    name: docker-ce
    state: present
    update_cache: true

# Запуск сервиса Docker через systemd:
- name: Start Docker service on RedHat family distro
  service:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

# Проверка того, был ли запущен docker.service в системе:
- name: Check if Docker is working now on RedHat family distro
  systemd:
    name: docker
  register: docker_service_status

# Результат выполненной ранее проверки:
- name: The result of our test on RedHat family distro
  debug:
    var: docker_service_status.status.ActiveState
