---
# # Активация маршрутизации в системе, для будущей сборки образа Docker через Ansible (опционально, так как не всегда возникала ошибка):
# - name: Active routing for build docker image on RedHat family distro
#   command: echo net.ipv4.ip_forward=1 > /etc/sysctl.conf

# Создание группы docker в используемой системе:
- name: Ensure group "docker" exists on RedHat family distro
  group:
    name: docker
    state: present

# Добавление репозитория для последующей установки Docker в системе:
- name: Adding package repository address on RedHat family distro
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true

# Загрузка дополнительного RPM-пакета из Интернета, для установки Docker в системе (актуально для Centos 9):
- name: Installing a libcgroup package on RedHat family distro
  yum:
    name: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/libcgroup-0.41-19.el8.x86_64.rpm
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '9'

# Установка Docker с помощью пакетного менеджера:
- name: Installing Docker on RedHat family distro
  yum:
    name: docker-ce
    state: present
    update_cache: true

# Запуск сервиса Docker через systemd:
- name: Starting Docker service on RedHat family distro
  service:
    name: docker
    state: started
    enabled: true

# Проверка того, был ли запущен docker.service в системе:
- name: Check if Docker is working now on RedHat family distro
  systemd:
    name: docker
  register: docker_service_status

# Результат выполненной ранее проверки:
- name: The result of our test on RedHat family distro
  debug:
    var: docker_service_status.status.ActiveState

# Проверка того, установлен ли Docker-compose в системе:
- name: Check if docker-compose is installed on RedHat family distro
  command: "{{ docker_compose_dest }} --version"
  register: docker_compose_check
  ignore_errors: true
  changed_when: false

# Установка Docker-compose в случае его отсуствия в системе:
- name: Installing docker-compose on RedHat family distro
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "{{ docker_compose_dest }}"
    mode: 'a+x'
    force: true
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
