---
# Создание группы docker в используемой системе:
- name: Ensure that docker group exists on SUSE family distro
  group:
    name: docker
    state: present

# Установка Docker с помощью пакетного менеджера:
- name: Install Docker on SUSE family distro
  zypper:
    name: docker
    state: present
    update_cache: true

# Запуск сервиса Docker через systemd:
- name: Start Docker service on SUSE family distro
  service:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

# Проверка того, был ли запущен docker.service в системе:
- name: Check if Docker is working now on SUSE family distro
  systemd:
    name: docker
  register: docker_service_status

# Результат выполненной ранее проверки:
- name: The result of our test on SUSE family distro
  debug:
    var: docker_service_status.status.ActiveState

# Проверка того, установлен ли Docker-compose в системе:
- name: Check if docker-compose is installed on SUSE family distro
  command: "{{ docker_compose_destination }} --version"
  register: docker_compose_check
  ignore_errors: true
  changed_when: false

# Установка Docker-compose в случае его отсуствия в системе:
- name: Install docker-compose on SUSE family distro
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "{{ docker_compose_destination }}"
    mode: 'a+x'
    force: true
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
