---
# Создание группы docker в используемой системе:
- name: Ensure that docker group exists on SUSE family distro
  group:
    name: docker
    state: present

# Установка Docker с помощью пакетного менеджера:
- name: Install Docker on SUSE family distro
  zypper:
    name: "{{ suse_docker_package }}"
    state: present
    update_cache: true

# Запуск сервиса Docker через systemd:
- name: Start Docker service on SUSE family distro
  service:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

# Проверка того, был ли запущен docker.service в системе:
- name: Check if Docker is working now on SUSE family distro
  systemd:
    name: docker
  register: docker_service_status

# Результат выполненной ранее проверки:
- name: The result of our test on SUSE family distro
  debug:
    var: docker_service_status.status.ActiveState

# Создание директории для установки плагина Compose в Docker:
- name: Create Docker Compose directories on SUSE family distro (Only SLES)
  file:
    state: directory
    path: "{{ suse_docker_compose_dir }}"
    mode: "0755"
    owner: "0"
    group: "0"
    recurse: true

# Загрузка плагина Compose для работы с Docker:
- name: Download Docker Compose plugin on SUSE family distro (Only SLES)
  get_url:
    url: " {{ suse_docker_compose_link }}"
    dest: "{{ suse_docker_compose_dir }}/docker-compose"
    mode: "0755"
