---
# Создание группы docker в используемой системе:
- name: Ensure that docker group exists on SUSE family distro
  group:
    name: docker
    state: present

# Установка Docker с помощью пакетного менеджера:
- name: Install Docker on SUSE family distro
  zypper:
    name: "{{ suse_docker_package }}"
    state: present
    update_cache: true

# Запуск сервиса Docker через systemd:
- name: Start Docker service on SUSE family distro
  service:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

# Проверка того, был ли запущен docker.service в системе:
- name: Check if Docker is working now on SUSE family distro
  systemd:
    name: docker
  register: docker_service_status

# Результат выполненной ранее проверки:
- name: The result of our test on SUSE family distro
  debug:
    var: docker_service_status.status.ActiveState
