---
# Вызов предварительной роли system-prepare для полноценного запуска текущей:
- name: Import system-prepare role for running main role on RedHat family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Создание файла, добавление ключа и адреса репозитория Jenkins в yum.repos.d:
- name: Add package repository address on RedHat family distro
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    gpgcheck: true
    baseurl: "{{ redhat_yum_repository }}"
    gpgkey: "{{ redhat_yum_key }}"

# Установка необходимых пакетов для успешного запуска Jenkins:
- name: Install required packages on RedHat family distro
  yum:
    name: "{{ redhat_packages_list }}"
    state: present

# Копирование файлов из директории files и их последующая передача в рабочую директорию Jenkins:
- name: Copy plugin file in work directory Jenkins on RedHat family distro
  copy:
    src: files/plugins.txt
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Копирование Systemd файла из директории templates и его последующая передача в рабочую директорию Jenkins:
- name: Copy custom Jenkins systemd config on RedHat family distro
  template:
    src: templates/jenkins.redhat.service.j2
    dest: "/usr/lib/systemd/system/{{ jenkins_systemd_filename }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "0"
    group: "0"

# Загрузка утилиты из Github-репозитория для автоматической установки всех плагинов в Jenkins:
- name: Download Plugin Installation Manager for installing plugins from file plugins.txt on RedHat family distro
  get_url:
    url: "{{ jenkins_plugin_manager }}"
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Непосредственно сама установка всех плагинов с помощью утилиты Plugin Installation Manager в Jenkins:
- name: Install all plugins using the Plugin Installation Manager on RedHat family distro
  shell: cd {{ jenkins_working_dir }} && java -jar jenkins-plugin-manager-*.jar -w {{ jenkins_war_path }} -d plugins -f plugins.txt
  changed_when: false

# Изменение прав у директории plugins после установки плагинов из файла plugins.txt в Jenkins:
- name: Change directory permissions after installing plugins on RedHat family distro
  file:
    path: "{{ jenkins_plugins_dir }}"
    mode: "{{ jenkins_plugin_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
    recurse: true
  changed_when: false

# Создание директорий для хранения CasC конфигурации в Jenkins:
- name: Create CasC configuration directory on RedHat family distro
  file:
    state: directory
    path: "{{ jenkins_casc_dir }}"
    mode: "{{ jenkins_working_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Запуск и добавление в автозагрузку сервиса Jenkins с помощью systemd:
- name: Start Jenkins service on RedHat family distro
  service:
    name: jenkins
    state: started
    enabled: true
    daemon_reload: true

# Копирование конфигурационных файлов из директории templates и их последующая передача в рабочую директорию Jenkins:
- name: Copy template CasC configs in directory casc_configs on RedHat family distro
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_casc_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
  with_fileglob:
    - ../templates/*.yaml.j2
  changed_when: false

# Перезапуск сервиса Jenkins с помощью systemd после удаления конфигурационных файлов CasC:
- name: Restart Jenkins service on RedHat family distro
  service:
    name: jenkins
    state: restarted
  changed_when: false

# Регистрация содержимого директории для последующего удаления:
- name: Get directory listing on RedHat family distro
  find:
    paths: "{{ jenkins_casc_dir }}"
    patterns: '*'
    hidden: true
  register: directory_content_result

# Удаление конфигурационных файлов CasC после завершения установки (подробнее о причинах удаления в README):
- name: Remove CasC files from directory on RedHat family distro
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ directory_content_result.files }}"
  changed_when: false
