---
# Создание файла, добавление ключа и адреса репозитория Jenkins в yum.repos.d:
- name: Adding package repository address on RedHat family distro
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    gpgcheck: true
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

# Установка необходимых пакетов для успешного запуска Jenkins:
- name: Installing required packages on RedHat family distro
  yum:
    name: "{{ centos_packages_list }}"
    state: present

# Создание директорий для хранения CasC конфигурации в Jenkins:
- name: Create CasC configuration directory on RedHat family distro
  file:
    state: directory
    path: "{{ jenkins_casc_dir }}"
    mode: "{{ jenkins_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Копирование файлов из директории files и их последующая передача в рабочую директорию Jenkins:
- name: Copy plugin file in work directory Jenkins on RedHat family distro
  copy:
    src: files/plugins.txt
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Копирование файлов из директории templates и их последующая передача в рабочую директорию Jenkins:
- name: Copy template jcasc configs in directory casc_configs on RedHat family distro
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_casc_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
  with_fileglob:
    - ../templates/*.yaml.j2
  failed_when: false

# Копирование файлов из директории templates и их последующая передача в рабочую директорию Jenkins:
- name: Copy custom Jenkins systemd config on RedHat family distro
  template:
    src: templates/jenkins.redhat.service.j2
    dest: "/usr/lib/systemd/system/{{ jenkins_systemd_filename }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "0"
    group: "0"

# Загрузка утилиты из Github-репозитория для автоматической установки всех плагинов в Jenkins:
- name: Download Plugin Installation Manager for installing plugins from file plugins.txt on RedHat family distro
  get_url:
    url: "{{ jenkins_plugin_manager }}"
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Непосредственно сама установка всех плагинов с помощью утилиты Plugin Installation Manager в Jenkins:
- name: Installing all plugins using the Plugin Installation Manager on RedHat family distro
  shell: cd {{ jenkins_working_dir }} && java -jar jenkins-plugin-manager-*.jar -w {{ jenkins_war_path }} -d plugins -f plugins.txt
  changed_when: false

# Изменение прав у директории plugins после установки плагинов из файла plugins.txt в Jenkins:
- name: Changing directory permissions after installing plugins on RedHat family distro
  file:
    path: "{{ jenkins_plugins_dir }}"
    mode: "{{ jenkins_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
    recurse: true
  changed_when: false

# Запуск и добавление в автозагрузку сервиса Jenkins с помощью systemd:
- name: Starting Jenkins service on RedHat family distro
  service:
    name: jenkins
    state: started
    enabled: true
    daemon_reload: true
