---
# Вызов предварительной роли system-prepare для полноценного запуска текущей:
- name: Import system-prepare role for running main role on SUSE family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Добавление GPG ключа для последующей установки Jenkins из пакетного менеджера:
- name: Import GPG key to ensure your software on SUSE family distro
  rpm_key:
    key: "{{ opensuse_zypper_key }}"
    state: present

# Создание файла и добавление адреса репозитория Jenkins в zypp.repos.d:
- name: Add package repository address on SUSE family distro
  zypper_repository:
    name: jenkins
    state: present
    repo: "{{ opensuse_zypper_repository }}"

# Установка необходимых пакетов для успешного запуска Jenkins:
- name: Install required packages on SUSE family distro
  zypper:
    name: "{{ opensuse_packages_list }}"
    state: present

# Создание директорий для хранения CasC конфигурации в Jenkins:
- name: Create CasC configuration directory on SUSE family distro
  file:
    state: directory
    path: "{{ jenkins_casc_dir }}"
    mode: "{{ jenkins_working_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Копирование файлов из директории files и их последующая передача в рабочую директорию Jenkins:
- name: Copy plugin file in work directory Jenkins on SUSE family distro
  copy:
    src: files/plugins.txt
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Копирование файлов из директории templates и их последующая передача в рабочую директорию Jenkins:
- name: Copy template CasC configs in directory casc_configs on SUSE family distro
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_casc_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
  with_fileglob:
    - ../templates/*.yaml.j2
  changed_when: false
  failed_when: false

# Копирование файлов из директории templates и их последующая передача в рабочую директорию Jenkins:
- name: Copy custom Jenkins systemd config on SUSE family distro
  template:
    src: templates/jenkins.suse.service.j2
    dest: "/usr/lib/systemd/system/{{ jenkins_systemd_filename }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "0"
    group: "0"

# Загрузка утилиты из Github-репозитория для автоматической установки всех плагинов в Jenkins:
- name: Download Plugin Installation Manager for installing plugins from file plugins.txt on SUSE family distro
  get_url:
    url: "{{ jenkins_plugin_manager }}"
    dest: "{{ jenkins_working_dir }}"
    mode: "{{ jenkins_file_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"

# Непосредственно сама установка всех плагинов с помощью утилиты Plugin Installation Manager в Jenkins:
- name: Install all plugins using the Plugin Installation Manager on SUSE family distro
  shell: cd {{ jenkins_working_dir }} && java -jar jenkins-plugin-manager-*.jar -w {{ jenkins_war_path }} -d plugins -f plugins.txt
  changed_when: false

# Изменение прав у директории plugins после установки плагинов из файла plugins.txt в Jenkins:
- name: Change directory permissions after installing plugins on SUSE family distro
  file:
    path: "{{ jenkins_plugins_dir }}"
    mode: "{{ jenkins_plugin_dir_mode }}"
    owner: "{{ jenkins_file_owner }}"
    group: "{{ jenkins_file_group }}"
    recurse: true
  changed_when: false

# Исправление ошибки, из-за которой добавление в автозагрузку не срабатывает по умолчанию (только для SUSE):
- name: Change filename to fix systemd error on SUSE family distro
  shell: if [ -e /etc/init.d/jenkins ]; then mv /etc/init.d/jenkins /etc/init.d/jks; else exit 0; fi
  changed_when: false

# Запуск и добавление в автозагрузку сервиса Jenkins с помощью systemd:
- name: Start Jenkins service on SUSE family distro
  service:
    name: jenkins
    state: started
    enabled: true
    daemon_reload: true

# Регистрация содержимого директории для последующего удаления:
- name: Get directory listing on SUSE family distro
  find:
    paths: "{{ jenkins_casc_dir }}"
    patterns: '*'
    hidden: true
  register: directory_content_result

# Удаление конфигурационных файлов CasC после завершения установки (подробнее о причинах удаления в README):
- name: Remove CasC files from directory on SUSE family distro
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ directory_content_result.files }}"
  changed_when: false

# Перезапуск сервиса Jenkins с помощью systemd после удаления конфигурационных файлов CasC:
- name: Restart Jenkins service on SUSE family distro
  service:
    name: jenkins
    state: restarted
  changed_when: false
