---
  # Добавление ключа репозитория для последующей установки Jenkins из пакетного менеджера:
  - name: Add Jenkins apt repository key
    get_url:
      url: "{{ ubuntu_apt_key }}"
      dest: "{{ ubuntu_dest_key }}"
      mode: "0644"
      force: true

  # Добавление адреса репозитория Jenkins в sources.list:
  - name: Adding package repository address to sources.list on Ubuntu
    apt_repository:
      repo: "deb [signed-by={{ ubuntu_dest_key }}] {{ ubuntu_apt_repository }} binary/"
      state: present
      filename: jenkins
      update_cache: yes

  # Установка необходимых пакетов, которые были определены в переменной:
  - name: Installing required packages on Ubuntu
    apt: 
      name: "{{ ubuntu_packages_list }}"
      state: present

  # Запуск сервиса Jenkins через systemd:
  - name: Starting Jenkins service on Ubuntu
    service:
      name: jenkins
      state: started
      enabled: yes

  # Вывод пароля от Jenkins для первого входа в консоль исполнения:
  - name: Printing the Jenkins password to the console from the file 
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: first_jenkins_password
  - debug:
      msg: "{{ first_jenkins_password.stdout }}"
