---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  tasks:

    # Данный шаг вызывает роль system-docker для прогона тестов:
    - name: "Include system-docker role for testing"
      include_role:
        name: "system-docker"
