---
version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    image: jenkins-master
    user: jenkins
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - /opt/jenkins_config:/var/jenkins_config/casc_configs
      - /opt/jenkins_data:/var/jenkins_home
      - /opt/jenkins_backup:/var/jenkins_backup
    networks:
      - jenkins
    restart: on-failure

networks:
  jenkins:
    name: jenkins
    driver: bridge
