---

# Переменные, необходимые для конфигурирования Jenkins Agent, применимые на всех дистрибутивах в равной мере:
jenkins_agent_template_mode: "u=rw,g=r,o=r"
jenkins_agent_directory_mode: "u=rwx"
jenkins_agent_directory:
  - main: /var/lib/jenkins
    ssh: /var/lib/jenkins/.ssh

# Переменные, необходимые для конфигурировании Jenkins Agent, применимые на дистрибутиве OpenSUSE:

opensuse_agent_packages_list:
  - java-11-openjdk

# Переменные, необходимые для конфигурировании Jenkins Agent, применимые на дистрибутиве Centos:

centos_agent_packages_list:
  - java-11-openjdk

# Переменные, необходимые для конфигурировании Jenkins Agent, применимые на дистрибутиве Ubuntu:

ubuntu_agent_packages_list:
  - openjdk-11-jdk
