---
dependency:
  name: galaxy

driver:
  name: ec2

platforms:
  # # Для запуска данного образа может понадобится подписка в AWS Marketplace.
  # - name: "CentOS 8"
  #   aws_profile: "{{ aws_profile }}"
  #   region: "{{ aws_region }}"
  #   image_name: " (SupportedImages) - Docker - CentOS 8 x86_64 - 20250204-ed9e8665-8abd-45e7-a2aa-3621b42eb3d1" # CentOS 8
  #   image_owner: "679593333241"
  #   instance_type: "{{ aws_instance_type }}"
  #   vpc_id: "{{ aws_vpc_id }}"
  #   vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
  #   volumes: []
  #   security_groups: []
  #   key_inject_method: "{{ aws_key_method }}"
  #   ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
  #   ssh_port: 22
  #   assign_public_ip: true
  #   boot_wait_seconds: 120
  #   key_name: "{{ aws_custom_key_name }}"
  #   private_key_path: "{{ aws_local_private_key }}"
  #   public_key_path: "{{ aws_local_public_key }}"
  #   security_group_name: "{{ aws_secruity_group_name }}"

  # # Для запуска данного образа может понадобится подписка в AWS Marketplace.
  # - name: "CentOS 9"
  #   aws_profile: "{{ aws_profile }}"
  #   region: "{{ aws_region }}"
  #   image_name: " (SupportedImages) - CentOS 9 x86_64 LATEST - 20250204-517790b7-f180-43d0-8fb9-bcb60760cc17" # CentOS 9
  #   image_owner: "679593333241"
  #   instance_type: "{{ aws_instance_type }}"
  #   vpc_id: "{{ aws_vpc_id }}"
  #   vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
  #   volumes: []
  #   security_groups: []
  #   key_inject_method: "{{ aws_key_method }}"
  #   ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
  #   ssh_port: 22
  #   assign_public_ip: true
  #   boot_wait_seconds: 120
  #   key_name: "{{ aws_custom_key_name }}"
  #   private_key_path: "{{ aws_local_private_key }}"
  #   public_key_path: "{{ aws_local_public_key }}"
  #   security_group_name: "{{ aws_secruity_group_name }}"

  - name: "Red Hat 8"
    aws_profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_name: "RHEL-8.10.0_HVM-20250121-x86_64-1662-Hourly2-GP3" # RHEL 8.10
    image_owner: "309956199498"
    instance_type: "{{ aws_instance_type }}"
    vpc_id: "{{ aws_vpc_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    volumes: []
    security_groups: []
    key_inject_method: "{{ aws_key_method }}"
    ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
    ssh_port: 22
    assign_public_ip: true
    boot_wait_seconds: 120
    key_name: "{{ aws_custom_key_name }}"
    private_key_path: "{{ aws_local_private_key }}"
    public_key_path: "{{ aws_local_public_key }}"
    security_group_name: "{{ aws_secruity_group_name }}"

  - name: "Red Hat 9"
    aws_profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_name: "RHEL-9.5.0_HVM-20250128-x86_64-0-Hourly2-GP3" # RHEL 9.5
    image_owner: "309956199498"
    instance_type: "{{ aws_instance_type }}"
    vpc_id: "{{ aws_vpc_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    volumes: []
    security_groups: []
    key_inject_method: "{{ aws_key_method }}"
    ssh_user: "{{ aws_default_ubuntu_ssh_user }}"
    ssh_port: 22
    assign_public_ip: true
    boot_wait_seconds: 120
    key_name: "{{ aws_custom_key_name }}"
    private_key_path: "{{ aws_local_private_key }}"
    public_key_path: "{{ aws_local_public_key }}"
    security_group_name: "{{ aws_secruity_group_name }}"

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    links:
      group_vars: ../../../../group_vars/

verifier:
  name: ansible
