---
# Переменные, необходимые для установки и настройки мануального Jenkins, применимые ко всем дистрибутивам в равной степени:

jenkins_working_dir: "/var/lib/jenkins"
jenkins_casc_dir: "{{ jenkins_working_dir }}/casc_configs"
jenkins_plugins_dir: "{{ jenkins_working_dir }}/plugins"
jenkins_working_dir_mode: "u=rwx,g=rx,o=rx"
jenkins_plugin_dir_mode: "u=rwx,g=rx,o=rx"
jenkins_file_mode: "u=rw,g=r,o=r"
jenkins_file_owner: jenkins
jenkins_file_group: jenkins
jenkins_war_path: /usr/share/java/jenkins.war
jenkins_systemd_filename: jenkins.service
jenkins_plugin_manager: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.13/jenkins-plugin-manager-2.12.13.jar

# Переменные, необходимые для конфигурирования мануального Jenkins на дистрибутиве семейства SUSE:

suse_zypper_key: https://pkg.jenkins.io/opensuse/jenkins.io-2023.key
suse_zypper_repository: https://pkg.jenkins.io/opensuse-stable/
suse_packages_list:
  - java-11-openjdk
  - dejavu-fonts
  - fontconfig
  - jenkins

# Переменные, необходимые для установки пакетов на дистрибутиве семейства Redhat:

redhat_yum_key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
redhat_yum_repository: https://pkg.jenkins.io/redhat-stable
redhat_packages_list:
  - java-11-openjdk
  - java-11-openjdk-devel
  - fontconfig
  - jenkins

# Переменные, необходимые для установки пакетов на дистрибутиве семейства Debian:

debian_apt_key: "https://pkg.jenkins.io/debian/jenkins.io-2023.key"
debian_dest_key: "/etc/apt/trusted.gpg.d/jenkins.asc"
debian_apt_repository: "http://pkg.jenkins.io/debian-stable"
debian_packages_list:
  - openjdk-17-jdk
  - openjdk-17-jre
  - fontconfig

debian_old_packages_list:
  - openjdk-11-jdk
  - fontconfig

debian_package_jenkins:
  - jenkins
