---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  tasks:
    # Данный шаг вызывает роль docker-jenkins-agent для прогона тестов с помощью Molecule:
    - name: "Include docker-jenkins-agent role for testing"
      include_role:
        name: "docker-jenkins-agent"
