---
# Вызов нескольких ролей для запуска и настройки Jenkins через Docker на удаленных узлах:
- name: Installing and configuring Jenkins via Docker on remote hosts
  gather_facts: yes
  become: yes
  hosts: 
    - all

  pre_tasks:
    # Вызов роли system-prepare для последующей установки всех необходимых пакетов:
    - name: Running a role for preparing remote systems
      include_role:
        name: system-prepare
        tasks_from: main.yaml

    # Вызов роли Docker для проверки на наличие приложения в системе:
    - name: Check if Docker is installed on remote hosts
      command: docker info
      register: docker_check
      ignore_errors: true

    # Вызов роли Docker для установки, со всеми необходимыми компонентами, для будущего запуска Jenkins через Docker на удаленных узлах:
    - name: Installing Docker on remote hosts, before Jenkins
      include_role:
        name: system-docker
        tasks_from: main.yaml
      when:
        - docker_check is failed

    # Оповещение в случае изначально установленного Docker в системе:
    - name: Output in case of installed Docker
      debug:
        msg: On this instance Docker is installed
      when: docker_check is succeeded

  roles:
    - docker-jenkins
