---
# Вызов нескольких ролей для последующей установки и настройки Jenkins с помощью Docker на удаленных узлах:
- name: Install and configure Jenkins via Docker on remote hosts
  gather_facts: true
  become: true
  become_method: sudo
  hosts:
    - all

  # Вызов непосредственно самой роли Docker Jenkins, для последующего развертывания Jenkins через Docker в системе:
  roles:
    - docker-jenkins

  # Информирование о том, что Jenkins с помощью Docker был успешно установлен в системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Jenkins has been successfully installed on the system"
