---
# Вызов нескольких ролей для запуска и настройки Jenkins через Docker на удаленных узлах:
- name: Installing and configuring Jenkins via Docker on remote hosts
  gather_facts: true
  become: true
  hosts:
    - all

  # Вызов непосредственно самой роли, для последующей установки Jenkins с помощью Docker:
  roles:
    - docker-jenkins

  # Вывод сообщения на предмет того, что Jenkins был успешно установлен и запущен в системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Jenkins has been successfully installed on the system"
