---
# Вызов роли для последующей установки и настройки Jenkins Master из пакетного менеджера:
- name: Installing and configuring Jenkins on remote hosts
  gather_facts: yes
  become: yes
  become_method: sudo
  hosts:
    - all
  roles:
    - manual-jenkins
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your manual Jenkins has been successfully installed on the system"
