---
# Вызов роли для последующей установки и настройки Jenkins Agent в ручную:
- name: Preparing the system as a running Jenkins Agent
  gather_facts: yes
  become: yes
  become_method: sudo
  hosts:
    - all
  roles:
    - manual-jenkins-agent
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Jenkins Agent has been successfully installed on the system"
