---

# Переменные, необходимые для установки пакетов, применимые ко всем дистрибутивам в равной степени:

# Переменные, необходимые для установки и настройки Docker на дистрибутиве семейства SUSE:

suse_docker_package:
  - docker
  - docker-compose 
  - docker-bash-completion

# Переменные, необходимые для установки и настройки Docker на дистрибутиве семейства RedHat:

redhat_docker_libcgroup: https://kojihub.stream.centos.org/kojifiles/packages/libcgroup/0.41/19.el8/x86_64/libcgroup-0.41-19.el8.x86_64.rpm

# Переменные, необходимые для установки и настройки Docker на дистрибутиве семейства Debian:

debian_docker_apt_repository: https://download.docker.com/linux/{{ ansible_distribution | lower}}
debian_docker_apt_key: https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg
debian_docker_destination_key: /etc/apt/trusted.gpg.d/docker.asc
debian_docker_file_mode: "u=rw,g=r,o=r"
