---
# Обновление всех пакетов на указанном дистрибутиве:
- name: Update all packages on Debian family distro
  apt:
    name: '*'
    state: latest
    update_cache: true
  tags:
    - update

# Установка пакетов apt из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install required packages on Debian family distro
  apt:
    name: "{{ ubuntu_packages_list }}"
    state: present
    update_cache: true

# Установка пакетов pip из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install required packages for pip on Debian family distro
  pip:
    name: "{{ pip_packages_list }}"
    state: present
    executable: pip3
