---
# Обновление всех пакетов для указанного семейства дистрибутивов:
- name: Update all packages on RedHat family distro
  yum:
    name: '*'
    state: latest
    update_cache: true
  tags:
    - update

# Установка пакетов RPM из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install general packages on RedHat family distro
  yum:
    name: "{{ redhat_packages_list }}"
    state: present
    update_cache: true
