---
  # Обновление всех пакетов на указанном дистрибутиве:
  - name: Updating all packages on OpenSUSE
    zypper:
      name: '*'
      state: latest
      update_cache: yes
    tags: 
      - update

  # Установка пакетов rpm из списка необходимых, которые определены в виде переменной, в директории defaults:
  - name: Installing required packages on OpenSUSE
    zypper: 
      name: "{{ opensuse_packages_list }}"
      state: present
      update_cache: yes

  # Установка пакетов pip из списка необходимых, которые определены в виде переменной, в директории defaults:
  - name: Installing required packages for pip on OpenSUSE
    pip:
      name: "{{ pip_packages_list }}"
      state: present
