---
# Обновление всех пакетов на указанном дистрибутиве:
- name: Update all packages on SUSE family distro
  zypper:
    name: '*'
    state: latest
    update_cache: true
  tags:
    - update

# Установка пакетов rpm из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install required packages on SUSE family distro
  zypper:
    name: "{{ opensuse_packages_list }}"
    state: present
    update_cache: true

# Установка пакетов pip из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install required packages for pip on SUSE family distro
  pip:
    name: "{{ pip_packages_list }}"
    state: present
    executable: pip3
