---
# Обновление всех пакетов на указанном дистрибутиве:
- name: Update all packages on SUSE family distro
  zypper:
    name: '*'
    state: latest
    update_cache: true
  tags:
    - update

# Установка пакетов rpm из списка необходимых, которые определены в виде переменной, в директории defaults:
- name: Install general packages on SUSE family distro
  zypper:
    name: "{{ suse_packages_list }}"
    state: present
    update_cache: true
