---
dependency:
  name: galaxy
driver:
  name: docker
  parallel: true
platforms:
  - name: opensuse_15
    image: opensuse:test
    dockerfile: opensuse.Dockerfile
    pre_build_image: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: centos_8
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: debian_11
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu_2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    capabilities:
      - SYS_ADMIN
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
  exit 0