---
# Включение HTTPS трафика на дистрибутиве:
- name: Enable httpd trafic via SELinux on Centos
  command: setsebool -P httpd_can_network_connect 1
  changed_when: false

# Установка Nginx с помощью пакетного менеджера:
- name: Installing required packages on Centos
  yum:
    name: "{{ nginx_package_list }}"
    state: present
    update_cache: true

# Передача конфигурационного файла Nginx для проксирования, при обращении к Jenkins через Интернет:
- name: Copy Nginx config for Jenkins on Centos
  template:
    src: templates/jenkins-master.conf.j2
    dest: "/etc/nginx/conf.d/{{ jenkins_nginx_domain }}.conf"
    mode: "{{ nginx_file_mode }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"

# Запуск сервиса Nginx через systemd:
- name: Starting Nginx service on Centos
  systemd:
    name: nginx
    state: started
    enabled: true

# Регистрация проверки конфигурации Nginx в переменную:
- name: Output of command Nginx -t after changes on Centos
  command: nginx -t
  register: nginx_validate
  failed_when: false
  changed_when: false

# Результат вывода переменной на экран:
- name: The output result of our variable on Centos
  debug:
    var: nginx_validate.stderr
