---
  # Включение HTTPS трафика на дистрибутиве:
  - name: Enable httpd trafic via SELinux on Centos
    shell: setsebool -P httpd_can_network_connect 1

  # Установка Nginx с помощью пакетного менеджера:
  - name: Installing required packages on Centos
    yum: 
      name: "{{ nginx_package_list }}"
      state: present
      update_cache: yes

  # Передача конфигурационного файла Nginx для проксирования, при обращении к Jenkins через Интернет:
  - name: Copy Nginx config for Jenkins on Centos
    template:
      src: templates/jenkins-master.conf.j2
      dest: "/etc/nginx/conf.d/{{ jenkins_nginx_domain }}.conf"
      mode: "{{ nginx_file_mode }}"
      owner: "{{ nginx_file_owner }}"
      group: "{{ nginx_file_group }}"

  # Запуск сервиса Nginx через systemd:
  - name: Starting Nginx service on Centos
    systemd:
      name: nginx
      state: started
      enabled: yes

  # Проверка конфигурационного файла после его добавления в систему:
  - name: Output of command Nginx -t after changes on Centos
    shell: nginx -t
    register: command_output
    ignore_errors: true
  - debug: msg="{{ command_output.stderr }}"
