---
# Установка Nginx с помощью пакетного менеджера:
- name: Install required packages on Debian family distro
  apt:
    name: "{{ nginx_package_list }}"
    state: present
    update_cache: true

# Удаление стандартной конфигурации Nginx в системе:
- name: Delete default Nginx configuration on Debian family distro
  file:
    state: absent
    path: "{{ item.path }}"
  with_items:
    - {path: "/etc/nginx/sites-available/default"}
    - {path: "/etc/nginx/sites-enabled/default"}

# Передача конфигурационного файла Nginx для проксирования, при обращении к Jenkins через Интернет:
- name: Copy Nginx config for Jenkins on Debian family distro
  template:
    src: templates/jenkins-master.conf.j2
    dest: "/etc/nginx/sites-available/{{ jenkins_nginx_domain }}.conf"
    mode: "{{ nginx_file_mode }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
  notify: Restart Nginx

# Создание симлинка на конфигурационный файл из available в enabled:
- name: Create a symlink on Debian family distro
  file:
    src: "/etc/nginx/sites-available/{{ jenkins_nginx_domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ jenkins_nginx_domain }}.conf"
    state: link

# Регистрация проверки конфигурации Nginx в переменную:
- name: Register the output of command nginx -t after changes on Debian family distro
  command: nginx -t
  register: nginx_validate
  failed_when: false
  changed_when: false

# Результат вывода переменной на экран:
- name: The output result of our variable on Debian family distro
  debug:
    var: nginx_validate.stderr

# Запуск сервиса Nginx через systemd:
- name: Start Nginx service on Debian family distro
  systemd:
    name: nginx
    state: started
    daemon_reload: true
    enabled: true
