---
# Установка Nginx с помощью пакетного менеджера:
- name: Installing required packages on SUSE family distro
  zypper:
    name: "{{ nginx_package_list }}"
    state: present
    update_cache: true

# Передача конфигурационного файла Nginx для проксирования, при обращении к Jenkins через Интернет:
- name: Copy Nginx config for Jenkins on SUSE family distro
  template:
    src: templates/jenkins-master.conf.j2
    dest: "/etc/nginx/conf.d/{{ jenkins_nginx_domain }}.conf"
    mode: "{{ nginx_file_mode }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
  notify: Restart Nginx

# Регистрация проверки конфигурации Nginx в переменную:
- name: Register the output of command Nginx -t after changes on SUSE family distro
  command: nginx -t
  register: nginx_validate
  failed_when: false
  changed_when: false

# Результат вывода переменной на экран:
- name: The output result of our variable on SUSE family distro
  debug:
    var: nginx_validate.stderr

# Запуск сервиса Nginx через systemd:
- name: Starting Nginx service on SUSE family distro
  systemd:
    name: nginx
    state: started
    daemon_reload: true
    enabled: true
