---
  # Установка Nginx с помощью пакетного менеджера:
  - name: Installing required packages on Ubuntu
    apt: 
      name: "{{ nginx_package }}"
      state: present
      update_cache: yes

  # Запуск сервиса Nginx через systemd:
  - name: Starting Nginx service on Ubuntu
    systemd:
      name: nginx
      state: started
      enabled: yes
    ignore_errors: true

  # Удаление стандартной конфигурации Nginx в системе:
  - name: Delete default Nginx configuration on Ubuntu
    file:
      state: absent
      path: /etc/nginx/sites-available/default

  # Передача конфигурационного файла Nginx для проксирования, при обращении к Jenkins через Интернет:
  - name: Copy Nginx config for Jenkins on Ubuntu
    template:
      src: templates/jenkins-master.conf.j2
      dest: "/etc/nginx/sites-available/{{ jenkins_nginx_domain }}.conf"
      mode: "{{ nginx_file_mode }}"
      owner: "{{ nginx_file_owner }}"
      group: "{{ nginx_file_group }}"
    notify: Restarting Nginx

  # Создание симлинка на конфигурационный файл из доступных сайтов в активные:
  - name: Creating a symlink on Ubuntu
    file:
      src: "/etc/nginx/sites-available/{{ jenkins_nginx_domain }}.conf"
      dest: "/etc/nginx/sites-enabled/{{ jenkins_nginx_domain }}.conf"
      state: link

  # Проверка конфигурационного файла после его добавления в систему:
  - name: Output of command Nginx -t after changes on Ubuntu
    shell: nginx -t
    register: command_output
    ignore_errors: true
  - debug: msg="{{ command_output.stderr }}"
